enabled: true # Whether the plugin should be active or not

toggle: # features for the /pvp command
  timer: 0 # Duration in seconds for how long the player has to stand still to toggle pvp
  cooldown: 0 # Cooldown in seconds between toggling pvp from off to on. (0 == disabled)
  aliases: # Aliases for the command
    - togglePvp
    - togglepvp
    - pvpToggle
    - pvptoggle

force-pvp:
  aliases:
    - forcepvp

combat:
  combat-duration: 60 # Duration in seconds that player cannot exit pvp after being attacked
  self-damage: true # Whether players should take damage from themselves while pvp is off (won't tag them either way)
  keep-inventory: true # Should players keep their inventory when another player kills them
  disable-pvp-on-death: true # Should pvp be disabled for players when they die

environment:
  fire-death-counts: true # Should dying to fire while in combat count as a pvp death (e.g. fire aspect)
  lava:
    enabled: true # Should placing lava cause the lava to be treated as a combat action (combat tag and such)
    immunity-time: 2 # How long (in seconds) should it take for pvp lava immunity to wear off