name: Yappp
version: '1.0-SNAPSHOT'
main: io.github.lamelemon.yappp.Yappp
api-version: '1.21.11'
authors: [ lamius lemonius ]
description: Yet Another Pvp Protection Plugin for Papermc
website: https://github.com/lamelemon/Yappp.git
